import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 11

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window.padding]
x = 0
y = 0


